version: '3'

services:
  db:
    image: postgres:9.5
    container_name: hamsteri-database
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=hamsteri
     - POSTGRES_PASSWORD=hamsteri
     - POSTGRES_DB=hamsteri
  backend:
    image: kiekkohamsteri-backend
    ports:
     - "8080:80"
    depends_on:
     - db
    container_name: kiekkohamsteri-backend
    environment:
     - CLOUDINARY_URL
     - HAMSTERI_JWT_SECRET
     - HAMSTERI_GOOGLE_CLIENT_ID
     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hamsteri
     - SPRING_DATASOURCE_USERNAME=hamsteri
     - SPRING_DATASOURCE_PASSWORD=hamsteri
