name: Build and upload

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  ECR_REPOSITORY: kiekkohamsteri-dev
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker build and push to Github Packages
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CROSS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CROSS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ECR_ROLE_ARN }}
          role-duration-seconds: 1800
          role-session-name: GithubAction-ECR-PushDeploy
      - name: Build and push docker image
        run: |
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY ${{ secrets.CONTAINER_REGISTRY_HOST }}/$ECR_REPOSITORY
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.CONTAINER_REGISTRY_HOST }}
          docker push ${{ secrets.CONTAINER_REGISTRY_HOST }}/$ECR_REPOSITORY
