name: Build, upload and deploy to dev

on:
  push:
    branches: [ "main" ]

env:
  ECR_REPOSITORY: kiekkohamsteri-dev

jobs:
  build:
    runs-on: ubuntu-latest
    name: Docker build and push to ECR
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CROSS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CROSS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          role-to-assume: ${{ secrets.KIEKKOHAMSTERI_CICD_ROLE }}
          role-duration-seconds: 1800
          role-session-name: GithubAction-ECR-PushDeploy
      - name: Build and push docker image
        run: |
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY ${{ secrets.CONTAINER_REGISTRY_HOST }}/$ECR_REPOSITORY
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.CONTAINER_REGISTRY_HOST }}
          docker push ${{ secrets.CONTAINER_REGISTRY_HOST }}/$ECR_REPOSITORY

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Update TD on ECS service

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CROSS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CROSS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          role-to-assume: ${{ secrets.KIEKKOHAMSTERI_CICD_ROLE }}
          role-duration-seconds: 1800
          role-session-name: GithubAction-ECS-Update-TD
      - name: Download TD
        run: |
          aws ecs describe-task-definition --task-definition kiekkohamsteri-task-dev --query taskDefinition > task-definition.json
      - name: Update TD
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: kiekkohamsteri-dev-container
          image: ${{ secrets.CONTAINER_REGISTRY_HOST }}/$ECR_REPOSITORY:latest
      - name: Deploy TD
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: kiekkohamsteri-dev-service
          cluster: kiekkohamsteri-dev
          wait-for-service-stability: true
